#!/bin/bash
# First edit:   2023/02/20 Mon 03:48 -0800
# Last edit:    2024/01/16 Tue 11:34 -0800 
# Got from here & added a few things:
# https://www.reddit.com/r/archlinux/comments/15a5n4/comment/c7krxnq/


usage="    `basename $0` file_to_uncompress.ext
Will extract/uncompress a variety of filetypes. Type of compression applied will be determined by filename extension."
[ "$#" -eq 0 ] && echo "$usage" && exit 0

shopt -qs nocasematch
for filename in $*
do if [ -f "$filename" ]
then case "$filename" in
    *.tar.bz2)        tar xvjf "$filename"      ;;
    *.tar.gz)         tar xvzf "$filename"      ;;
    *.tar.xz)         tar xf "$filename"      ;;
    *.bz2)            bunzip2 "$filename"      ;;
    *.rar)            unrar x "$filename"        ;;
    *.gz)             gunzip "$filename"        ;;
    *.tar|*.dmp)      tar xvf "$filename"     ;;
    *.tbz2)           tar xvjf "$filename"       ;;
    *.tgz)            tar xvzf "$filename"       ;;
    *.zip)            unzip "$filename"          ;;
    *.Z)              uncompress "$filename" ;;
    *)                echo "'"$filename"' cannot be extracted via extract()"  ;;
esac
else
    echo "'$1' is not a valid file"
fi
done
shopt -qu nocasematch

